<?php
// Script to count total power generated by 興達新CC#1 and 興達新CC#2
// Each record represents MW generated in 10 minutes

$dataDir = '/home/kiang/public_html/taipower_data/docs/genary/2025';
$totalCC1 = 0;  // 興達新CC#1
$totalCC2 = 0;  // 興達新CC#2
$recordCount = 0;
$workingHoursCC1 = 0;  // Hours CC#1 was working (generation > 0)
$workingHoursCC2 = 0;  // Hours CC#2 was working (generation > 0)

// Target unit names to search for
$targetUnits = [
    '興達新CC#1' => 'CC1',
    '興達新CC#2' => 'CC2'
];

function processJsonFile($filePath, &$totalCC1, &$totalCC2, &$recordCount, &$workingHoursCC1, &$workingHoursCC2) {
    global $targetUnits;
    
    if (!file_exists($filePath)) {
        return;
    }
    
    $content = file_get_contents($filePath);
    if ($content === false) {
        echo "Error reading file: $filePath\n";
        return;
    }
    
    $data = json_decode($content, true);
    if ($data === null) {
        echo "Error decoding JSON in file: $filePath\n";
        return;
    }
    
    if (!isset($data['aaData']) || !is_array($data['aaData'])) {
        echo "No aaData found in file: $filePath\n";
        return;
    }
    
    $recordCount++;
    
    foreach ($data['aaData'] as $record) {
        if (!is_array($record) || count($record) < 5) {
            continue;
        }
        
        $unitName = trim($record[2]);
        // Generated power is in column 5 (index 4)
        $generatedPower = floatval($record[4]);
        
        // Check for 興達新CC#1 (with possible notation like (註10))
        if (strpos($unitName, '興達新CC#1') !== false) {
            $totalCC1 += $generatedPower;
            if ($generatedPower > 0) {
                $workingHoursCC1 += (10/60); // Add 10 minutes = 1/6 hour
            }
            echo "Found CC#1 in $filePath: $unitName = $generatedPower MW\n";
        }
        
        // Check for 興達新CC#2 (with possible notation like (註10))
        if (strpos($unitName, '興達新CC#2') !== false) {
            $totalCC2 += $generatedPower;
            if ($generatedPower > 0) {
                $workingHoursCC2 += (10/60); // Add 10 minutes = 1/6 hour
            }
            echo "Found CC#2 in $filePath: $unitName = $generatedPower MW\n";
        }
    }
}

// Scan all directories in the data directory
if (is_dir($dataDir)) {
    $dateDirs = scandir($dataDir);
    
    foreach ($dateDirs as $dateDir) {
        if ($dateDir === '.' || $dateDir === '..') {
            continue;
        }
        
        $datePath = $dataDir . '/' . $dateDir;
        if (!is_dir($datePath)) {
            continue;
        }
        
        echo "Processing directory: $dateDir\n";
        
        // Scan JSON files in each date directory
        $jsonFiles = glob($datePath . '/*.json');
        
        foreach ($jsonFiles as $jsonFile) {
            processJsonFile($jsonFile, $totalCC1, $totalCC2, $recordCount, $workingHoursCC1, $workingHoursCC2);
        }
    }
} else {
    echo "Error: Data directory not found: $dataDir\n";
    exit(1);
}

echo "\n=== SUMMARY ===\n";
echo "Total JSON files processed: $recordCount\n";
echo "興達新CC#1 total power generated: " . number_format($totalCC1, 2) . " MW\n";
echo "興達新CC#2 total power generated: " . number_format($totalCC2, 2) . " MW\n";
echo "Combined total: " . number_format($totalCC1 + $totalCC2, 2) . " MW\n";
echo "\n=== WORKING HOURS ===\n";
echo "興達新CC#1 working hours: " . number_format($workingHoursCC1, 2) . " hours\n";
echo "興達新CC#2 working hours: " . number_format($workingHoursCC2, 2) . " hours\n";
echo "興達新CC#1 working days: " . number_format($workingHoursCC1 / 24, 2) . " days\n";
echo "興達新CC#2 working days: " . number_format($workingHoursCC2 / 24, 2) . " days\n";
echo "\nNote: Each record represents MW generated in a 10-minute interval\n";

// Convert to MWh (megawatt-hours) by dividing by 6 (since 10 minutes = 1/6 hour)
$totalCC1_MWh = $totalCC1 / 6;
$totalCC2_MWh = $totalCC2 / 6;
$combined_MWh = ($totalCC1 + $totalCC2) / 6;

echo "\n=== ENERGY SUMMARY (MWh) ===\n";
echo "興達新CC#1 total energy: " . number_format($totalCC1_MWh, 2) . " MWh\n";
echo "興達新CC#2 total energy: " . number_format($totalCC2_MWh, 2) . " MWh\n";
echo "Combined total energy: " . number_format($combined_MWh, 2) . " MWh\n";

?>